############################
# BASIC CLUSTER SETTINGS
############################

ClusterName=primrose

SlurmctldHost=primrose-frontend001

SlurmUser=slurm

AuthType=auth/munge
# (Recommended for new clusters: AuthType=auth/slurm)

StateSaveLocation=/var/spool/slurm
SlurmdSpoolDir=/var/lib/slurm/slurmd

############################
# NODES
############################

NodeName=primrose-med128compute001 CPUs=30 Sockets=1 CoresPerSocket=30 ThreadsPerCore=1 RealMemory=11700 State=UNKNOWN
#NodeName=XXXXXXXXXXX CPUs=XX Sockets=X CoresPerSocket=XX ThreadsPerCore=1 RealMemory=XX State=UNKNOWN

############################
# PARTITIONS
############################

PartitionName=main \
    Nodes=primrose-med128compute001 \
    Default=YES \
    MaxTime=INFINITE \
    State=UP

############################
# SCHEDULER
############################

SchedulerType=sched/backfill

SelectType=select/cons_tres
SelectTypeParameters=CR_Core_Memory

############################
# PRIORITY
############################

PriorityType=priority/multifactor

#PriorityWeightAge=12500
#PriorityWeightFairshare=100000
PriorityWeightJobSize=12500
PriorityWeightPartition=0
PriorityWeightQOS=20000

#PriorityDecayHalfLife=14-0
#PriorityUsageResetPeriod=NONE
#PriorityMaxAge=7-0
PriorityFavorSmall=NO

############################
# ACCOUNTING
############################

AccountingStorageType=accounting_storage/none
#AccountingStorageEnforce=associations,limits,qos
#AccountingStoreFlags=job_comment

JobCompType=jobcomp/none

############################
# ACCOUNTING GATHERING
############################

JobAcctGatherType=jobacct_gather/linux
JobAcctGatherFrequency=60

AcctGatherEnergyType=acct_gather_energy/none
AcctGatherFilesystemType=acct_gather_filesystem/none
AcctGatherInfinibandType=acct_gather_infiniband/none
AcctGatherProfileType=acct_gather_profile/none

############################
# GRES
############################

GresTypes=gpu

############################
# JOB CONTROL
############################

JobRequeue=1

MaxArraySize=1000
MaxJobCount=10000

ProctrackType=proctrack/cgroup
TaskPlugin=task/cgroup

PropagateResourceLimits=NONE
ReturnToService=2
TmpFS=/tmp

############################
# TIMEOUTS
############################

BatchStartTimeout=60
CompleteWait=35
InactiveLimit=0
KillWait=30
MinJobAge=300

############################
# CONTROLLER
############################

SlurmctldPort=6817
SlurmctldTimeout=300

SlurmctldDebug=error
SlurmctldLogFile=/var/log/slurm/slurmctld.log

DebugFlags=backfill,cpu_bind,priority,reservation,selecttype,steps

############################
# COMPUTE DAEMON
############################

SlurmdPort=6818
SlurmdTimeout=300

SlurmdDebug=error
SlurmdLogFile=/var/log/slurm/slurmd.log

DisableRootJobs=NO

MailProg=/bin/true

############################
# RECOMMENDED FOR 25.x
############################

SlurmctldParameters=enable_configless
SlurmdParameters=config_overrides
